### ISSUE TITLE
naturalLog2# to complement integerLog2#

### ISSUE THREAD

**Issue by andrewthad** [haskellari/integer-logarithms#25]
Sometimes, I need

    naturalLog2# :: Natural -> Int#

This doesn't seem difficult to add, and I'm happy to give it a try, but I don't think `GHC.Integer.Logarithms.Compat` is the right place for it. Maybe `GHC.Natural.Logarithms.Compat`?

**Comment by phadej** [comment]
`GHC.Integer.Logarithms` compat the https://hackage.haskell.org/package/integer-gmp-1.0.2.0/docs/GHC-Integer-Logarithms.html module. There is no `GHC.Natural.Logarithms`.

I'd say you have to pave the road so `GHC.Natural.Logarithms` would be in `base`, and then `integer-logarithms` could provide *compat* versions for older GHCs (or `base-compat`).

**Comment by phadej** [comment]
There is `naturalLog2`
