### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by leungbk** [haskellari/integer-logarithms#34]
Since it's been nearly two years since the last release was cut, it would be nice if we could have one soon.

GHC 9.0.2 and above include versions of `ghc-bignum` that are >= 1.1. However, the latest release (but not the latest `master`) imposes

https://github.com/haskellari/integer-logarithms/blob/a54ae7adbc579d1c665a5f19d32bdd3fd797d200/integer-logarithms.cabal#L68

cc @phadej

**Comment by Bodigrim** [comment]
@leungbk the latest release already supports GHC 9.0 and above: https://hackage.haskell.org/package/integer-logarithms-1.0.3.1/dependencies

**Comment by leungbk** [comment]
> @leungbk the latest release already supports GHC 9.0 and above: https://hackage.haskell.org/package/integer-logarithms-1.0.3.1/dependencies

That's interesting, why does the `cabal` file from release 1.0.3.1 I linked not match the Hackage `cabal` file from the same release you've linked? Apologies, I'm not very familiar with the Haskell ecosystem.

**Comment by leungbk** [comment]
OK, I see that there can be revisions to metadata.
